theme: jekyll-theme-chirpy
remote_theme: cotes2020/chirpy
title: Kubelessons
tagline: Learn and practice Kubernetes
description: >-
  A place to learn Kubernetes with MiniKube and practice with mock exams.
lang: en
timezone: Europe/Amsterdam